### ISSUE TITLE
Corporate Members are receiving email cleanup messages

### ISSUE THREAD

**Issue by vanderaj** [OWASP-Foundation/owaspadmin-azurefunctions#7]
Corporate members are receiving the owasp.org email clean up messages. They don't have an owasp.org email address. 

We can address this in two ways:

Stop sending it to them
Provisioning them all (~ 58) with emails

In either case, please stop sending them messages if they do not have owasp.org emails as their primary contact.

**Comment by OWASPFoundation** [comment]
This is overcome by events; there will be no more emails regarding email deactivation going to our non-owasp.org lists (Mailchimp).
